---
- hosts: all
  remote_user: centos
  vars:
    authorized_key_list:
      - name: centos
        authorized_keys:
         - key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
           state: present
#  roles:
 #   - { role: GROG.authorized-key }
